#spring.application.name=MVC_promo_acition
#spring.datasource.username=Kirill
#spring.datasource.password=191919
#spring.datasource.url=jdbc:postgresql://localhost:5432/promo_db
#spring.data.jdbc.dialect=postgresql
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=create

spring:
  application:
    name: MVC_promo_acition
  datasource:
    url: jdbc:postgresql://localhost:5432/promo_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: true

  security:
    user:
      name: admin
      password: admin


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB



